---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewStarterRugProject"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.24.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "cff978c59d1635572a8de584f1a1daad5e8d7a68"
    sha: "cff978c"
  parameters:
    - "project_name": "workflow-handlers"

